-----Query 1 - How badly do Americans procrastinate on their taxes? -------
SELECT EXTRACT(MONTH FROM t.firstQuery),EXTRACT(DAY FROM t.firstQuery), count(*) FROM (
	SELECT FACTS.ANONID as id, min(TIMEDIM.DATETIME) as firstQuery FROM
	FACTS
	JOIN TIMEDIM on FACTS.TIMEID=TIMEDIM.ID
	JOIN QUERYDIM on FACTS.QUERYID=QUERYDIM.ID
	WHERE (QUERYDIM.QUERY LIKE '% irs %'
	OR QUERYDIM.QUERY LIKE '%irs %'
	OR QUERYDIM.QUERY LIKE '%1040%'
	OR QUERYDIM.QUERY LIKE '%tax%')
	GROUP BY FACTS.ANONID) t
GROUP BY EXTRACT(MONTH FROM t.firstQuery),EXTRACT(DAY FROM t.firstQuery);
-----Query 2 - How many users have we geolocated by state -----------
SELECT STATES.STATE_ABBR, count(distinct FACTS.ANONID) FROM FACTS
JOIN STATES on FACTS.STATE_ID = STATES.ID
GROUP BY STATES.STATE_ABBR;

-----Query 3 - QUESTION 1: ---------
SELECT STATES.REGION
	, STATES.STATE_ABBR
	, AVG(t.attnSpan)
	, MEDIAN(t.attnSpan)
	, STDDEV(t.attnSpan)
FROM STATES 
JOIN (SELECT FACTS.STATE_ID as stateID
	, FACTS.ANONID as ID
	, QUERYDIM.QUERY as QUERY
	, min(TIMEDIM.DATETIME) as startTime
	, max(TIMEDIM.DATETIME) as endTime
	, SECONDS_BETWEEN(max(TIMEDIM.DATETIME),min(TIMEDIM.DATETIME)) as attnSpan
	FROM FACTS
	JOIN QUERYDIM on FACTS.QUERYID=QUERYDIM.ID
	JOIN TIMEDIM on FACTS.TIMEID=TIMEDIM.ID
	GROUP BY FACTS.STATE_ID,FACTS.ANONID,
		EXTRACT(MONTH FROM TIMEDIM.DATETIME),
		EXTRACT(DAY FROM TIMEDIM.DATETIME),
		QUERYDIM.QUERY
	HAVING SECONDS_BETWEEN(max(TIMEDIM.DATETIME),min(TIMEDIM.DATETIME))>0) t
on STATES.ID=t.stateID
GROUP BY ROLLUP(STATES.REGION, STATES.STATE_ABBR);

-----Query 4 - QUESTION 2: ---------
select STATES.STATE_NAME,
	STATES.REGION,
	median(FACTS.DATAPOINT) 'TW'
from FACTS
inner join STATES on STATES.ID = FACTS.STATE_ID
where FACTS.DATAPOINT != 0
group by rollup (STATES.REGION,STATES.STATE_NAME)
order by 1;

-----Query 5 - QUESTION 3: ---------
Select STATES.REGION,
		DMOZ_CATEGORIES.TOPIC_2,
		DMOZ_CATEGORIES.TOPIC_3,
		median(FACTS.DATAPOINT)
from FACTS
inner join STATES on STATES.ID = FACTS.STATE_ID
inner join QUERYDIM on QUERYDIM.ID = FACTS.QUERYID
inner join URLDIM on FACTS.URLID = URLDIM.ID
inner join URL_CATEGORY on URL_CATEGORY.URLID = URLDIM.ID
inner join DMOZ_CATEGORIES on DMOZ_CATEGORIES.CATID = URL_CATEGORY.CATEGORYID
where DMOZ_CATEGORIES.TOPIC_2 = 'Shopping' and FACTS.DATAPOINT != 0
group by cube (STATES.REGION,
		DMOZ_CATEGORIES.TOPIC_2,
		DMOZ_CATEGORIES.TOPIC_3);

-----Query 6 - QUESTION 4: ---------
SELECT STATES.REGION, STATES.STATE_ABBR, median(SECONDS_BETWEEN(TIMEDIM.DATETIME, userSession.starttime)), count(*)
FROM FACTS
JOIN URLDIM on FACTS.URLID = URLDIM.ID
JOIN QUERYDIM on FACTS.QUERYID = QUERYDIM.ID
JOIN TIMEDIM on FACTS.TIMEID  = TIMEDIM.ID
JOIN STATES on STATES.ID=FACTS.STATE_ID
JOIN (SELECT FACTS.ANONID as ID, QUERYDIM.QUERY as QUERY, min(TIMEDIM.DATETIME) as startTime, max(TIMEDIM.DATETIME) as endTime 
	FROM FACTS
	JOIN QUERYDIM on FACTS.QUERYID=QUERYDIM.ID
	JOIN TIMEDIM on FACTS.TIMEID=TIMEDIM.ID
	GROUP BY FACTS.ANONID,
		EXTRACT(MONTH FROM TIMEDIM.DATETIME),
		EXTRACT(DAY FROM TIMEDIM.DATETIME),
		QUERYDIM.QUERY
	ORDER BY 1) as userSession
ON to_char(userSession.STARTTIME, 'DD-MM-YYYY') = to_char(TIMEDIM.DATETIME, 'DD-MM-YYYY')
where userSession.ID = FACTS.ANONID 
and userSession.QUERY = QUERYDIM.QUERY 
and ( URLDIM.THISDOMAIN LIKE 'amazon'
OR URLDIM.THISDOMAIN LIKE 'amazon.%')
and SECONDS_BETWEEN(TIMEDIM.DATETIME, userSession.starttime)>0
GROUP BY ROLLUP(STATES.REGION,STATES.STATE_ABBR)
HAVING count(*)>10;
